/*
Copyright (c) 2020, VSB - Technical University of Ostrava and Graz University of
Technology
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice, this
  list of conditions and the following disclaimer in the documentation and/or
  other materials provided with the distribution.
* Neither the names of VSB - Technical University of  Ostrava and Graz
  University of Technology nor the names of its contributors may be used to
  endorse or promote products derived from this software without specific prior
  written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS”
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL VSB - TECHNICAL UNIVERSITY OF OSTRAVA AND
GRAZ UNIVERSITY OF TECHNOLOGY BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/** @file low_rank_kernel.h
 * @brief Auxiliary routines providing kernel evaluations for construction of
 * low rank matrices.
 */

#ifndef INCLUDE_BESTHEA_LOW_RANK_KERNEL_H_
#define INCLUDE_BESTHEA_LOW_RANK_KERNEL_H_

#include "besthea/settings.h"

namespace besthea {
  namespace bem {
    template< class T >
    class low_rank_kernel;
  }
}

/**
 * Pure virtual class representing a low-rank kernel for ACA approximation.
 * Using CRTP for static polymorphism.
 */
template< typename T >
class besthea::bem::low_rank_kernel {
 public:
  // low_rank_kernel( const low_rank_kernel & that ) = delete;
  ~low_rank_kernel( ){ };

  /**
   * Evaluate the matrix generated by the kernel at position (i,j).
   * The routine impyEval of the derived class is called.
   * \param[in] i   Row index.
   * \param[in] j   Column index.
   * \return Matrix entry at position (\p i,\p j).
   */
  sc evaluate( lo i, lo j ) const {
    return static_cast< const T * >( this )->implEval( i, j );
  }
};

namespace besthea {
  namespace bem {
    class kernel_from_matrix;
  }
}

/**
 * Simple class that allows to access entries of a full matrix via the
 * LowrankKernel class.
 */
class besthea::bem::kernel_from_matrix
  : public besthea::bem::low_rank_kernel< besthea::bem::kernel_from_matrix > {
 public:
  /**
   * Constructor for the matrix kernel
   */
  kernel_from_matrix( const besthea::linear_algebra::full_matrix * matrix )
    : _matrix( matrix ) {
  }

  /** Dummy evaluation of kernel
   * \param[in] i Row index
   * \param[in] j Column index
   * \return Matrix entry at (i, j)
   */
  inline sc implEval( lo i, lo j ) const {
    return _matrix->get( i, j );
  };

 private:
  const besthea::linear_algebra::full_matrix * _matrix;
};

#endif  // INCLUDE_BESTHEA_LOW_RANK_KERNEL_H_
