macro(setup_compiler)
  if (CMAKE_CXX_COMPILER_ID MATCHES GNU)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
    #set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wextra -pedantic-errors")
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 8.3)
      message(FATAL_ERROR "GCC compiler is too old, besthea can be"
        " compiled only with g++-8.3 or higher.")
    endif()
  elseif (CMAKE_CXX_COMPILER_ID MATCHES Intel)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -xHost -w2")
  else()
    message(FATAL_ERROR "Unknown C++ compiler: ${CMAKE_CXX_COMPILER_ID}.")
  endif()

  set(CMAKE_CXX_FLAGS_RELEASE "-O3")
  set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-g -O3")
  message(STATUS "Build type: ${CMAKE_BUILD_TYPE}")
endmacro()

macro(enable_OpenMP)
  find_package(OpenMP REQUIRED)

  message(STATUS "Found OpenMP.")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
endmacro()

macro(enable_Boost)
  #add_subdirectory(third_party/boost/align)
  include_directories(include third_party/boost/align/include)
  #add_subdirectory(third_party/boost/config)
  include_directories(include third_party/boost/config/include)
  #add_subdirectory(third_party/boost/assert)
  include_directories(include third_party/boost/assert/include)
  #add_subdirectory(third_party/boost/static_assert)
  include_directories(include third_party/boost/static_assert/include)
  #add_subdirectory(third_party/boost/core)
  include_directories(include third_party/boost/core/include)
endmacro()

macro(enable_Eigen)
  include_directories(include third_party/eigen)
endmacro()
